version: "2.1"

services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - /opt/sds/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - "/opt/env"
