# Generated by Django 4.2.16 on 2024-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receiptorder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
